# Generated by Django 5.0.3 on 2024-04-08 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_comment_datetime_alter_listing_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 8, 13, 16, 31, 344581, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 8, 13, 16, 31, 332610, tzinfo=datetime.timezone.utc)),
        ),
    ]
