# Generated by Django 5.0.3 on 2024-04-08 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_notifications_count_alter_comment_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='is_won',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 8, 14, 22, 52, 937409, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 8, 14, 22, 52, 926374, tzinfo=datetime.timezone.utc)),
        ),
    ]
