# Generated by Django 5.0.3 on 2024-04-08 14:37

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_notifications_is_won_alter_comment_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='is_won',
        ),
        migrations.AddField(
            model_name='listing',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 8, 14, 37, 42, 231583, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 8, 14, 37, 42, 220555, tzinfo=datetime.timezone.utc)),
        ),
    ]
